lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^(\d+)/add_item$', views.add_item, name='add_item')
]

superlist/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls))
]

lists/models.py
from django.db import models

class List(models.Model):
    pass


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

lists/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from lists.models import Item, List

def home_page(request):
    return render(request, 'home.html')

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    return render(request, 'lists.html', {'list': list_})

def new_list(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect(f'/lists/{list_.id}/')

def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect(f'/lists/{list_.id}/')

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>To-Do lists</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/mdb/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="/static/mdb/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="/static/mdb/css/mdb.min.css" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="/static/mdb/css/style.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="header flex-center flex-column">
            <div class="to-do-list-card card">
                <h1 class="card-header info-color white-text text-center py-4">
                    <strong>{% block header_text %}{% endblock %}</strong>
                </h1>
                <div class="card-body px-lg-5 animated fadeIn">
                    <form method="POST" class="text-center" action="{% block form_action %}{% endblock %}">
                        {% csrf_token %}
                        <div class="md-form mt-3">
                            <input type="text" name="item_text" id="id_new_item" placeholder="Enter a to-do item">
                        </div>
                        <button class="btn btn-outline-info btn-rounded btn-block z-depth-0 my-4 waves-effect" type="submit">Add Item</button>
                    </form>

                    {% block content_table %}
                    {% endblock %}
                </div>
            </div>
        </div> <!-- /header -->

        <div class="content flex-center flex-column">
        </div> <!-- /content -->
    </div> <!-- /container -->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="/static/mdb/js/jquery-3.3.1.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="/static/mdb/js/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="/static/mdb/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="/static/mdb/js/mdb.min.js"></script>
</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}/lists/new{% endblock %}

lists/templates/lists.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}/lists/{{ list.id }}/add_item{% endblock %}

{% block content_table %}

    <hr>
    <ul id="id_list_table">
        {% for item in list.item_set.all %}
            <li>{{ forloop.counter }}: {{ item.text }}</li>
        {% endfor %}
    </ul>
{% endblock %}